### ISSUE TITLE
Unify NORMAL_MOTOR_STEPS <++> and/or split it to Robot config.h

### ISSUE THREAD

**Issue by cad435** [cad435/Makelangelo-firmware#5]
DEFAULT_FEEDRATE, DEFAULT_ACCELERATION, DEGREES_PER_STEP, MM_PER_STEP,   defined in robot_<MACHINE>.h will always get redefined in configureMotors.h

Option 1: delete setting in robot_<MACHINE>.h and configure it globally in configureMotors.h
Option 2: delete setting in  configureMotors.h and transfer it to seperate robot_<MACHINE>.h 

Advantage Option 2: different machines can have predefined values

Ask @i-make-robots for his opinion

**Comment by cad435** [comment]
If option 2 is prefered I need a list of default values for at least Sixi and Polygraph (those seem to be the main products for the software)

**Comment by i-make-robots** [comment]
I believe the defaults are already in reach robot_*.h.
ConfigMotors should have an #ifndef wrapper to be polite.

**Comment by cad435** [comment]
done
